export const endpoints = {
  LOGIN: "/token/",
  SIGNUP: "/rest-auth/registration/",
  PROFILE: "/api/me/",
  USERS_ME: "/api/users/",
  PERSON: "/api/persons/",
  MAIL_ACCOUNT: "/api/mail-accounts/",
  PROMPTS: "/api/prompts/",
  PLAYBOOKS: "/api/playbooks/",
  PROMPT_RESPONSES: "/api/prompt-responses/",
  EMAILS: "/api/emails/",
  ORGS: "/api/orgs/",
  IMPORT_PEOPLE: "/api/bulk-import/",
  SEQUENCE_EVENTS: "/api/sequence-events/",
  USER_DATA: "/api/user-data/",
  TEAMS: "/api/teams/",
  NEWPROMPT: "/api/new-prompt/",
  GOOGLEAUTH: "/google-auth/",
  MICROSOFTAUTH: "/microsoft-auth/",
  TEAM_MEMBERS: "/api/team-users/",
  API_GENERAL: "/api/",
  PAYMENTS: "/payments/",
};
