export const endpoints = {
  LOGIN: "/token/",
  SIGNUP: "/rest-auth/registration/",
  PROFILE: "/api/me/",
  USERS_ME: "/api/users/me/",
  PERSON: "/api/persons/",
  MAIL_ACCOUNT: "/api/mail-accounts/",
  PROMPTS: "/api/prompts/",
  PLAYBOOKS: "/api/playbooks/",
  PROMPT_RESPONSES: "/api/prompt-responses/",
  EMAILS: "/api/emails/",
  ORGS: "/api/orgs/",
  IMPORT_PEOPLE: "/api/bulk-import/",
  SEQUENCE_EVENTS: "/api/sequence-events/",
  USERS: "/api/users/",
};
